services:
  - type: web
    name: contribution-graph-pop-quiz
    runtime: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_USER_ID
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: LEETCODE_USERNAME
        value: _mitraboga
      - key: LEETCODE_START_DATE
        value: '2026-10-07'
      - key: TZ
        value: Asia/Kolkata
